version: '3'

services:
  database:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: 2G
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=myStrongPassword12#
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - my-network

  web-app:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    image: kmilchev1994bazarscr.azurecr.io/softunibazar
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - my-network
    domainname: kmilchev

networks:
  my-network:
    driver: bridge

volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: kmilchev1994bazarsa
